<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>GitUI.Git</RootNamespace>
    <AssemblyName>GitUI.Git</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GitUI.Git.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitUI.Core\GitUI.Core.csproj" />
    <ProjectReference Include="..\GitUI.Diff\GitUI.Diff.csproj" />
  </ItemGroup>

</Project>
