<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>GitUI.ViewModels</RootNamespace>
    <AssemblyName>GitUI.ViewModels</AssemblyName>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitUI.Core\GitUI.Core.csproj" />
  </ItemGroup>

</Project>
