# gen-localization.ps1 - 从 Strings.tsv 生成本地化资源（docs/i18n.md §二）
#
# 输入：src/GitUI.Core/Resources/Strings.tsv
#   每行：key <TAB> en <TAB> zh-Hans；# 开头为注释行；值内换行写作 \n
# 输出（同目录，均为生成产物，可随 TSV 重新生成）：
#   Strings.resx          中性资源（英文，NeutralResourcesLanguage=en）
#   Strings.zh-Hans.resx  简体中文卫星资源
#   Strings.Designer.cs   强类型访问器（public class Strings）
#
# 校验（失败即退出非零，不写产物）：
#   key 格式与唯一性、访问器名（. 转 _）唯一、zh 无缺项、占位符 {n} 中英一致
param(
    [string]$ResourceDir = (Join-Path $PSScriptRoot '..\src\GitUI.Core\Resources')
)

$ErrorActionPreference = 'Stop'
$tsvPath = Join-Path $ResourceDir 'Strings.tsv'
if (-not (Test-Path $tsvPath)) { Write-Error "缺少 $tsvPath" }

# ---- 解析 TSV ----
$entries = @()
$lineNo = 0
foreach ($raw in [System.IO.File]::ReadAllLines($tsvPath)) {
    $lineNo++
    if ($raw -match '^\s*#' -or $raw.Trim().Length -eq 0) { continue }
    $parts = $raw -split "`t"
    if ($parts.Count -ne 3) { Write-Error ("{0}:{1}: 每行必须为 key<tab>en<tab>zh-Hans 三列" -f $tsvPath, $lineNo) }
    $key, $en, $zh = $parts[0], $parts[1], $parts[2]
    if ($key -notmatch '^[A-Za-z][A-Za-z0-9]*(\.[A-Za-z][A-Za-z0-9]*)*$') {
        Write-Error ("{0}:{1}: 非法 key '{2}'（仅允许 PascalCase 与点分段）" -f $tsvPath, $lineNo, $key)
    }
    $entries += [pscustomobject]@{ Key = $key; En = $en; Zh = $zh; Line = $lineNo }
}
if ($entries.Count -eq 0) { Write-Error "$tsvPath 无有效条目" }

# ---- 校验 ----
$dupKeys = $entries | Group-Object Key | Where-Object Count -gt 1
if ($dupKeys) { Write-Error ("重复 key: " + (($dupKeys | ForEach-Object Name) -join ', ')) }

$dupNames = $entries | ForEach-Object { $_.Key.Replace('.', '_') } | Group-Object | Where-Object Count -gt 1
if ($dupNames) { Write-Error ("key 转 _ 后访问器名冲突: " + (($dupNames | ForEach-Object Name) -join ', ')) }

$missing = @($entries | Where-Object { $_.Zh.Trim().Length -eq 0 })
if ($missing.Count -gt 0) { Write-Error ("zh-Hans 缺失: " + (($missing | ForEach-Object Key) -join ', ')) }

foreach ($e in $entries) {
    $phEn = [regex]::Matches($e.En, '\{\d+\}') | ForEach-Object Value | Sort-Object
    $phZh = [regex]::Matches($e.Zh, '\{\d+\}') | ForEach-Object Value | Sort-Object
    if ((@($phEn) -join '|') -ne (@($phZh) -join '|')) {
        Write-Error ("{0}: 占位符不一致 en='{1}' zh='{2}'" -f $e.Key, $e.En, $e.Zh)
    }
}

# ---- 生成 resx ----
function Convert-Value([string]$text) { return $text.Replace('\n', "`n") }
function Escape-Xml([string]$text) {
    return $text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

$resheader = @'
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
'@

function Write-Resx([string]$path, [string]$prop) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<!-- 由 scripts/gen-localization.ps1 从 Strings.tsv 生成，勿手工修改。 -->')
    [void]$sb.AppendLine('<root>')
    [void]$sb.AppendLine($resheader)
    foreach ($e in $entries) {
        $value = Escape-Xml (Convert-Value $e.$prop)
        [void]$sb.AppendLine(('  <data name="{0}" xml:space="preserve"><value>{1}</value></data>' -f $e.Key, $value))
    }
    [void]$sb.AppendLine('</root>')
    [System.IO.File]::WriteAllText($path, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
}

Write-Resx (Join-Path $ResourceDir 'Strings.resx') 'En'
Write-Resx (Join-Path $ResourceDir 'Strings.zh-Hans.resx') 'Zh'

# ---- 生成 Designer ----
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated>由 scripts/gen-localization.ps1 从 Strings.tsv 生成，勿手工修改。</auto-generated>')
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine('using System.Globalization;')
[void]$sb.AppendLine('using System.Resources;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace GitUI.Core.Resources;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// 本地化字符串强类型访问器（docs/i18n.md）。资源缺失时返回 key 本身而非抛错，')
[void]$sb.AppendLine('/// 缺项会在 key-parity 单测与生成器校验中提前暴露。')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('public static class Strings')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private static ResourceManager? _resourceManager;')
[void]$sb.AppendLine('    private static CultureInfo? _resourceCulture;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    /// <summary>覆盖资源查找文化；null = 当前线程 UI 文化（LanguageService 已预设）。</summary>')
[void]$sb.AppendLine('    public static CultureInfo? Culture')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        get => _resourceCulture;')
[void]$sb.AppendLine('        set => _resourceCulture = value;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    private static ResourceManager ResourceManager =>')
[void]$sb.AppendLine('        _resourceManager ??= new ResourceManager("GitUI.Core.Resources.Strings", typeof(Strings).Assembly);')
[void]$sb.AppendLine('')
foreach ($e in $entries) {
    $literal = (Convert-Value $e.En).Replace('\', '\\').Replace('"', '\"').Replace("`n", '\n')
    $prop = $e.Key.Replace('.', '_')
    $line = '    public static string {0} => ResourceManager.GetString("{1}", _resourceCulture) ?? "{2}";' -f $prop, $e.Key, $literal
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText((Join-Path $ResourceDir 'Strings.Designer.cs'), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

Write-Output ("OK: {0} 条 → Strings.resx / Strings.zh-Hans.resx / Strings.Designer.cs" -f $entries.Count)
